### ISSUE TITLE
Epic: Universal Editor that can launch other editors (split this up!)

### ISSUE THREAD

**Issue by Synival** [Synival/sf3tools#74]
- [x] Rename project SF3Editor to SF3LibWin
- [x] Create highest-level project SF3Editor
- [x] Create "no file open" menu
   - [x] Open Disc
      - [x] Scenario auto-detection
   - [x] Open File
      - [x] Follow-up window to request 1) what kind of file, and 2) what disc
   - [x] Exit
- [x] Create "file open" menu
   - [x] Save
   - [x] Save As
   - [x] Close Current
- [ ] ~~Dynamic menu switching based on context~~ Won't do
- [ ] ~~Tabs for open discs/files~~ ~~Left pane browser view~~ Won't do
