### ISSUE TITLE
Epic: SF3DiscEditor

### ISSUE THREAD

**Issue by Synival** [Synival/sf3tools#75]
- [ ] Can't use EditorForm as a basis - need to make a completely new one
- [ ] All editors are categorized
- [ ] Add tables for big topics:
    - [ ] Icon Pointers
    - [ ] Items
    - [ ] Spells
    - [ ] (everything else in the X002 editor)
    - [ ] (all the random stuff in the X013 editor)
    - [ ] Monsters
    - [ ] Characters
    - [ ] Towns
    - [ ] Battles
    - [ ] Shops
    - [ ] Blacksmith
